.TH DESTROY 1 "Июнь 2024" "v1.0" "User Commands"
.SH NAME
destroy \- удалить репозиторий GitHub и локальный проект
.SH SYNOPSIS
.B destroy
имя_проекта
.SH DESCRIPTION
.B destroy
удаляет репозиторий на GitHub и соответствующую директорию проекта.

Конфигурация берётся из ~/.config/create/config.yaml.

Связанные утилиты: см. create(1).
.SH FILES
~/.config/create/config.yaml
.SH SEE ALSO
create(1)
.SH AUTHOR
Azarya Rozet 